from biblioteca import Pessoa

pessoa1 = Pessoa("yuri",70,18)

pessoa1.comer("")
pessoa1.falar()
pessoa1.falar()
pessoa1.dormir()
pessoa1.dormir()
pessoa1.falar()
pessoa1.falar()
pessoa1.comer("")
pessoa1.comer("")
pessoa1.acordar()
pessoa1.acordar()
pessoa1.falar()
pessoa1.falar()
pessoa1.comer("cachorro quente")
pessoa1.comer("")
pessoa1.pararFalar()
pessoa1.pararFalar()
pessoa1.comer("")
pessoa1.comer("pao")
pessoa1.comer("")
pessoa1.acordar()
pessoa1.comer("")